# This file used for both developer and demo purposes.
# It contains environment
version: '3.7'

services:
  # allows access from container to host
  docker-host:
    image: qoomon/docker-host:2.5.4
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    environment:
      - PORTS=6831,8060,8082,1235,1236,5443
    networks:
      frontend:
    restart: unless-stopped
  traefik:
    image: traefik:v2.4.0
    hostname: traefik
    restart: unless-stopped
    # The Static Configuration
    command: --configFile=/traefik_conf/traefik.yml
    networks:
      frontend:
    ports:
      - 8081:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik_conf:/traefik_conf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  # static server
  nginx:
    image: nginx:1.16.0
    restart: unless-stopped
    ports:
      - 8082:8082
    volumes:
      - ./frontend-nginx:/usr/share/nginx/html:ro
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
  postgresql:
    image: postgres:13.1
    restart: unless-stopped
    ports:
      - 35432:5432
    volumes:
      - ./docker/postgresql_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  redis:
    image: redis:6.0.8
    hostname: redis
    restart: unless-stopped
    ports:
      - 36379:6379
    volumes:
      - redis_data_dir:/data
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    hostname: minio
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      backend:
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio_data:/data
    command: ["server", "/data"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  openvidu:
    image: openvidu/openvidu-server-kms:2.16.0
    hostname: openvidu
    restart: unless-stopped
    ports:
      - 5443:5443
    networks:
      backend:
    environment:
      - SERVER_SSL_ENABLED=false
      - SERVER_PORT=5443
      - OPENVIDU_SECRET=MY_SECRET
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  jaeger:
    image: jaegertracing/all-in-one:1.18.1
    hostname: jaeger
    restart: unless-stopped
    ports:
      - 16686:16686 # web ui
      - 6831:6831/udp
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

volumes:
  postgres_data:
  redis_data_dir:
  minio_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    ipam:
      driver: default
      config:
        # Also see firewalld rule in readme.md "Allow container -> host"
        - subnet: 172.28.0.0/24
