# This file used for both developer and demo purposes.
# It contains environment
version: '3.7'

services:
  # static server
  nginx:
    image: nginx:1.16.0
    restart: unless-stopped
    ports:
      - 8081:80
    extra_hosts:
      # hosts to go outside from docker network to host-deployed chat app
      # When you apply firewalld rule these requests will go to you IDE-launched chat app
      # see also network definition in bottom
      - "api.site.local:172.28.0.1"
    networks:
      backend:
    volumes:
      - ./frontend-nginx:/usr/share/nginx/html:ro
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
  postgres:
    image: postgres:12.2
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: password
    networks:
      backend:
    ports:
      - 4432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  redis:
    image: redis:5.0.5
    hostname: redis
    restart: unless-stopped
    ports:
      - 36379:6379
    volumes:
      - redis_data_dir:/data
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

volumes:
  postgres_data:
  redis_data_dir:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        # Also see firewalld rule in readme.md "Allow container -> host"
        - subnet: 172.28.0.0/24
