http:
  middlewares:
    api-strip-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/api"
    retry-middleware:
      retry:
        attempts: 4
    auth-middleware:
      forwardAuth:
        address: "http://aaa:8060/internal/profile"
        authRequestHeaders:
          - "Cookie"
          - "uber-trace-id"
        authResponseHeadersRegex: "^X-Auth-"

