server:
  address: ":1236"
  shutdown.timeout: "10s"
  body.limit: "100G"
  contextPath: "/api"

auth:
  exclude:
    - "^/storage/public.*"

jaeger:
  host: "localhost"
  port: 6831

minio:
  endpoint: 127.0.0.1:9000
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  location: "europe-east"
  bucket:
    userAvatar: "user-avatar"
    chatAvatar: "chat-avatar"
    files: "files"
    embedded: "embedded"
  cleaner:
    embedded:
      # Start every
      interval: 90s
      # Max keys in batch
      maxKeys: 10
      # User has this time to send message with newly uploaded embedded image
      threshold: 300s
    files:
      # Start every
      interval: 60s
      # Max keys in batch
      maxKeys: 10

chat:
  url:
    base: "http://localhost:1235"
    access: "/internal/access"
    removeFileItem: "/internal/remove-file-item"
    checkEmbeddedFilesPath: "/internal/check-embedded-files"
    checkChatExistsPath: "/internal/is-chat-exists"
aaa:
  url:
    base: "http://localhost:8060"
    getUsers: "/internal/user/list"

limits:
  enabled: true
  stat:
    dir: "."
  default:
    # 512 megabytes
    all.users.limit: 536870912

redis:
  address: :36379
  password: ""
  db: 3
