# https://docs.traefik.io/reference/static-configuration/file/
global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  http:
    address: :8081
  traefik:
    address: :8083
providers:
  providersThrottleDuration: 2s
  docker:
    swarmMode: false
    watch: true
    exposedByDefault: false
  file:
    directory: /home/nkonev/go_1_11/videochat/docker/traefik_conf/dynamic
api:
  insecure: true
  dashboard: true
log:
  level: DEBUG
accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        X-B3-Traceid: keep
tracing:
  spanNameLimit: 150
  jaeger:
    gen128Bit: true
    localAgentHostPort: api.site.local:6831