server:
  address: ":1235"
  shutdown.timeout: "10s"
  body.limit: "2M"

# Rest client
http:
  maxIdleConns: 2
  idleConnTimeout: '10s'
  disableCompression: false

auth:
  exclude:
    - "^/chat/public.*"
    - "^/internal.*"

postgresql:
  # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
  url: "postgres://chat:chatPazZw0rd@postgresql:5432/chat?sslmode=disable&application_name=chat-app"
  maxOpenConnections: 16
  maxIdleConnections: 4
  maxLifetime: 30s

centrifuge:
  redis:
    address: "redis:6379"
    password: ""
    db: 1
    connectTimeout: 5s
    readTimeout: 30s
    writeTimeout: 30s
    idleTimeout: 60s

aaa:
  url:
    base: "http://aaa:8060"
    getUsers: "/internal/user/list"

rabbitmq:
  url: "amqp://videoChat:videoChatPazZw0rd@rabbitmq:5672"

jaeger:
  endpoint: "jaeger:6831"

redis:
  address: redis:6379
  password: ""
  db: 1
  connectTimeout: 5s
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 60s
  maxIdle: 1
  maxActive: 10

online:
  notification:
    period: 2s
