server:
  address: ":1235"
  shutdown.timeout: "10s"
  body.limit: "100G"

# Rest client
http:
  maxIdleConns: 2
  idleConnTimeout: '10s'
  disableCompression: false

auth:
  exclude:
    - "^/chat/public.*"
    - "^/internal.*"

postgresql:
  # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
  url: "postgres://chat:chatPazZw0rd@localhost:35432/chat?sslmode=disable&application_name=chat-app"
  maxOpenConnections: 16
  maxIdleConnections: 4
  maxLifetime: 30s

centrifuge:
  redis:
    address: "localhost:36379"
    password: ""
    db: 1
    connectTimeout: 5s
    readTimeout: 30s
    writeTimeout: 30s
    idleTimeout: 60s

aaa:
  url:
    base: "http://localhost:8060"
    getUsers: "/internal/user/list"

rabbitmq:
  url: "amqp://videoChat:videoChatPazZw0rd@127.0.0.1:36672"

jaeger:
  endpoint: "localhost:6831"

redis:
  address: :36379
  password: ""
  db: 1
  connectTimeout: 5s
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 60s
  maxIdle: 1
  maxActive: 10

online:
  notification:
    period: 2s