http:
  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8082
    aaa-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8060
    chat-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:1235
    storage-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:1236
    video-proxy-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:7000

  routers:
    frontend-router:
      rule: "PathPrefix(`/`)"
      service: frontend-service
      middlewares:
        - "retry-middleware"
    aaa-router:
      rule: "PathPrefix(`/api/login`) || Path(`/api/logout`) || PathPrefix(`/api/profile`) || PathPrefix(`/api/user`) || PathPrefix(`/api/oauth2`)"
      service: aaa-service
      middlewares:
        - "retry-middleware"
    chat-router:
      rule: "PathPrefix(`/api/chat`)"
      service: chat-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    storage-router:
      rule: "PathPrefix(`/api/storage`)"
      service: storage-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    video-router:
      rule: "PathPrefix(`/api/video`)"
      service: video-proxy-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
    chat-public-router:
      rule: "PathPrefix(`/api/chat/public`)"
      service: chat-service
      middlewares:
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    storage-public-router:
      rule: "PathPrefix(`/api/storage/public`)"
      service: storage-service
      middlewares:
        - "api-strip-prefix-middleware"
        - "retry-middleware"

  middlewares:
    api-strip-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/api"
    retry-middleware:
      retry:
        attempts: 4
    auth-middleware:
      forwardAuth:
        address: "http://host.docker.internal:8060/internal/profile"
        authRequestHeaders:
          - "Cookie"
          - "uber-trace-id"
        authResponseHeadersRegex: "^X-Auth-"
