http:
  services:
    nginx-service:
      loadBalancer:
        servers:
          - url: http://docker-host:8082
    aaa-service:
      loadBalancer:
        servers:
          - url: http://docker-host:8060
    chat-service:
      loadBalancer:
        servers:
          - url: http://docker-host:1235
    storage-service:
      loadBalancer:
        servers:
          - url: http://docker-host:1236
    openvidu-service:
      loadBalancer:
        servers:
          - url: http://docker-host:5443

  routers:
    nginx-router:
      rule: "PathPrefix(`/`)"
      service: nginx-service
      middlewares:
        - "retry-middleware"
    aaa-router:
      rule: "PathPrefix(`/api/login`) || Path(`/api/logout`) || PathPrefix(`/api/profile`) || PathPrefix(`/api/user`)"
      service: aaa-service
      middlewares:
        - "retry-middleware"
    chat-router:
      rule: "PathPrefix(`/api/chat`)"
      service: chat-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    storage-router:
      rule: "PathPrefix(`/api/storage`)"
      service: storage-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    chat-public-router:
      rule: "PathPrefix(`/api/chat/public`)"
      service: chat-service
      middlewares:
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    storage-public-router:
      rule: "PathPrefix(`/api/storage/public`)"
      service: storage-service
      middlewares:
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    openvidu-router:
      rule: "PathPrefix(`/api/video`)"
      service: openvidu-service
      middlewares:
        - "api-video-strip-prefix-middleware"
        - "auth-middleware"
        - "retry-middleware"

  middlewares:
    api-strip-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/api"
    api-video-strip-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/api/video"
    retry-middleware:
      retry:
        attempts: 4
    auth-middleware:
      forwardAuth:
        address: "http://docker-host:8060/internal/profile"
        authRequestHeaders:
          - "Cookie"
        authResponseHeadersRegex: "^X-Auth-"
